//
//  ComponentCell.swift
//  FFUFComponents
//
//  Created by Julio Miguel Alorro on 2/9/19.
//  Copyright © 2019 Feil, Feil, & Feil  GmbH. All rights reserved.
//

import class UIKit.UICollectionViewCell
import class UIKit.UIColor
import protocol LayoutKit.Layout
import struct CoreGraphics.CGFloat
import struct CoreGraphics.CGSize
import struct Foundation.IndexPath
import struct LayoutKit.LayoutMeasurement

/**
 The ComponentCell serves as the root UIView for the UI elements generated by its Layout
*/
open class ComponentCell: UICollectionViewCell {

    /**
     The String identifier used by the ComponentCell to register to a UICollectionView instance
     */
    open class var identifier: String {
        return String(describing: Mirror(reflecting: self).subjectType)
    }

    // MARK: Layout
    /**
     The current ComponentLayout instance that created and arranged the subviews in the contentView of this ComponentCell.
    */
    private var layout: ComponentLayout?

    override open func prepareForReuse() {
        super.prepareForReuse()
        self.layout = nil
    }

    override public final func layoutSubviews() {
        if let layout = self.layout {
            let measurement: LayoutMeasurement = layout.measurement(
                within: self.contentView.frame.size
            )

            measurement
                .arrangement(within: self.contentView.bounds)
                .makeViews(in: self.contentView)
        }
    }

    override public final func sizeThatFits(_ size: CGSize) -> CGSize {
        guard let size = self.layout?.measurement(within: size).size else { return CGSize.zero }
        return size
    }

    override public final var intrinsicContentSize: CGSize {
        return self.sizeThatFits(
            CGSize(
                width: Constants.screenWidth,
                height: CGFloat.greatestFiniteMagnitude
            )
        )
    }

    /**
     Binds the layout from the AnyComponent instance, sets the contentView.frame.size to the cell's intrinsicContentSize
     and calls setNeedsLayout.
    */
    open func configure(with component: AnyComponent) {
        self.layout = component.layout
        self.contentView.frame.size = self.intrinsicContentSize
        self.setNeedsLayout()
    }

}
