//
//  Cyanic
//  Created by Julio Miguel Alorro on 14.04.19.
//  Licensed under the MIT license. See LICENSE file
//

import LayoutKit
import UIKit

/**
 TableComponentCell serves as the root UIView for the UI elements generated by its Layout
*/
open class TableComponentCell: UITableViewCell {

    /**
     The String identifier used by the TableComponentCell to register to a UITableView instance
    */
    open class var identifier: String {
        return String(describing: Mirror(reflecting: self).subjectType)
    }

    // MARK: Layout
    /**
     The current ComponentLayout instance that created and arranged the subviews in the contentView of this TableComponentCell.
    */
    private var layout: ComponentLayout?

    override open func prepareForReuse() {
        super.prepareForReuse()
        self.layout = nil
    }

    override public final func sizeThatFits(_ size: CGSize) -> CGSize {
        guard let size = self.layout?.measurement(within: size).size else { return CGSize.zero }
        return size
    }

    override public final var intrinsicContentSize: CGSize {
        return self.sizeThatFits(
            CGSize(
                width: self.bounds.width,
                height: self.bounds.height
            )
        )
    }

    /**
     Reads the layout from the AnyComponent instance to create the subviews in this TableComponentCell instance. This also
     sets the contentView.frame.size to the cell's intrinsicContentSize and calls setNeedsLayout.
     - Parameters:
        - component: The AnyComponent instance that represents this TableComponentCell
    */
    open func configure(with component: AnyComponent) {
        self.layout = component.layout(width: self.contentView.bounds.width)
        self.contentView.frame.size = self.intrinsicContentSize

        self.layout?.arrangement(
            origin: self.contentView.bounds.origin,
            width: self.contentView.bounds.size.width,
            height: self.contentView.bounds.size.height
        )
            .makeViews(in: self.contentView)
    }

}
